package com.pm.intelligent.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pm.intelligent.bean.AdjustsEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ADJUSTS_ENTITY".
*/
public class AdjustsEntityDao extends AbstractDao<AdjustsEntity, Long> {

    public static final String TABLENAME = "ADJUSTS_ENTITY";

    /**
     * Properties of entity AdjustsEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ParamValue = new Property(1, String.class, "paramValue", false, "PARAM_VALUE");
        public final static Property ProtocolId = new Property(2, String.class, "protocolId", false, "PROTOCOL_ID");
        public final static Property HardwareConfId = new Property(3, int.class, "hardwareConfId", false, "HARDWARE_CONF_ID");
        public final static Property HardwareInfo = new Property(4, String.class, "hardwareInfo", false, "HARDWARE_INFO");
    }


    public AdjustsEntityDao(DaoConfig config) {
        super(config);
    }
    
    public AdjustsEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ADJUSTS_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"PARAM_VALUE\" TEXT," + // 1: paramValue
                "\"PROTOCOL_ID\" TEXT," + // 2: protocolId
                "\"HARDWARE_CONF_ID\" INTEGER NOT NULL UNIQUE ," + // 3: hardwareConfId
                "\"HARDWARE_INFO\" TEXT);"); // 4: hardwareInfo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ADJUSTS_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AdjustsEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String paramValue = entity.getParamValue();
        if (paramValue != null) {
            stmt.bindString(2, paramValue);
        }
 
        String protocolId = entity.getProtocolId();
        if (protocolId != null) {
            stmt.bindString(3, protocolId);
        }
        stmt.bindLong(4, entity.getHardwareConfId());
 
        String hardwareInfo = entity.getHardwareInfo();
        if (hardwareInfo != null) {
            stmt.bindString(5, hardwareInfo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AdjustsEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String paramValue = entity.getParamValue();
        if (paramValue != null) {
            stmt.bindString(2, paramValue);
        }
 
        String protocolId = entity.getProtocolId();
        if (protocolId != null) {
            stmt.bindString(3, protocolId);
        }
        stmt.bindLong(4, entity.getHardwareConfId());
 
        String hardwareInfo = entity.getHardwareInfo();
        if (hardwareInfo != null) {
            stmt.bindString(5, hardwareInfo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AdjustsEntity readEntity(Cursor cursor, int offset) {
        AdjustsEntity entity = new AdjustsEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // paramValue
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // protocolId
            cursor.getInt(offset + 3), // hardwareConfId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // hardwareInfo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AdjustsEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setParamValue(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProtocolId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHardwareConfId(cursor.getInt(offset + 3));
        entity.setHardwareInfo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AdjustsEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AdjustsEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AdjustsEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
