package com.pm.intelligent.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pm.intelligent.bean.AdjustsEntity;
import com.pm.intelligent.bean.AlarmInfoEntity;
import com.pm.intelligent.bean.FaultTrackEntity;
import com.pm.intelligent.bean.HomeShelterEntity;
import com.pm.intelligent.bean.ScenesEntity;
import com.pm.intelligent.bean.SearchHistory;
import com.pm.intelligent.bean.SwitchsEntity;

import com.pm.intelligent.greendao.AdjustsEntityDao;
import com.pm.intelligent.greendao.AlarmInfoEntityDao;
import com.pm.intelligent.greendao.FaultTrackEntityDao;
import com.pm.intelligent.greendao.HomeShelterEntityDao;
import com.pm.intelligent.greendao.ScenesEntityDao;
import com.pm.intelligent.greendao.SearchHistoryDao;
import com.pm.intelligent.greendao.SwitchsEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adjustsEntityDaoConfig;
    private final DaoConfig alarmInfoEntityDaoConfig;
    private final DaoConfig faultTrackEntityDaoConfig;
    private final DaoConfig homeShelterEntityDaoConfig;
    private final DaoConfig scenesEntityDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig switchsEntityDaoConfig;

    private final AdjustsEntityDao adjustsEntityDao;
    private final AlarmInfoEntityDao alarmInfoEntityDao;
    private final FaultTrackEntityDao faultTrackEntityDao;
    private final HomeShelterEntityDao homeShelterEntityDao;
    private final ScenesEntityDao scenesEntityDao;
    private final SearchHistoryDao searchHistoryDao;
    private final SwitchsEntityDao switchsEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adjustsEntityDaoConfig = daoConfigMap.get(AdjustsEntityDao.class).clone();
        adjustsEntityDaoConfig.initIdentityScope(type);

        alarmInfoEntityDaoConfig = daoConfigMap.get(AlarmInfoEntityDao.class).clone();
        alarmInfoEntityDaoConfig.initIdentityScope(type);

        faultTrackEntityDaoConfig = daoConfigMap.get(FaultTrackEntityDao.class).clone();
        faultTrackEntityDaoConfig.initIdentityScope(type);

        homeShelterEntityDaoConfig = daoConfigMap.get(HomeShelterEntityDao.class).clone();
        homeShelterEntityDaoConfig.initIdentityScope(type);

        scenesEntityDaoConfig = daoConfigMap.get(ScenesEntityDao.class).clone();
        scenesEntityDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        switchsEntityDaoConfig = daoConfigMap.get(SwitchsEntityDao.class).clone();
        switchsEntityDaoConfig.initIdentityScope(type);

        adjustsEntityDao = new AdjustsEntityDao(adjustsEntityDaoConfig, this);
        alarmInfoEntityDao = new AlarmInfoEntityDao(alarmInfoEntityDaoConfig, this);
        faultTrackEntityDao = new FaultTrackEntityDao(faultTrackEntityDaoConfig, this);
        homeShelterEntityDao = new HomeShelterEntityDao(homeShelterEntityDaoConfig, this);
        scenesEntityDao = new ScenesEntityDao(scenesEntityDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        switchsEntityDao = new SwitchsEntityDao(switchsEntityDaoConfig, this);

        registerDao(AdjustsEntity.class, adjustsEntityDao);
        registerDao(AlarmInfoEntity.class, alarmInfoEntityDao);
        registerDao(FaultTrackEntity.class, faultTrackEntityDao);
        registerDao(HomeShelterEntity.class, homeShelterEntityDao);
        registerDao(ScenesEntity.class, scenesEntityDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(SwitchsEntity.class, switchsEntityDao);
    }
    
    public void clear() {
        adjustsEntityDaoConfig.clearIdentityScope();
        alarmInfoEntityDaoConfig.clearIdentityScope();
        faultTrackEntityDaoConfig.clearIdentityScope();
        homeShelterEntityDaoConfig.clearIdentityScope();
        scenesEntityDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        switchsEntityDaoConfig.clearIdentityScope();
    }

    public AdjustsEntityDao getAdjustsEntityDao() {
        return adjustsEntityDao;
    }

    public AlarmInfoEntityDao getAlarmInfoEntityDao() {
        return alarmInfoEntityDao;
    }

    public FaultTrackEntityDao getFaultTrackEntityDao() {
        return faultTrackEntityDao;
    }

    public HomeShelterEntityDao getHomeShelterEntityDao() {
        return homeShelterEntityDao;
    }

    public ScenesEntityDao getScenesEntityDao() {
        return scenesEntityDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public SwitchsEntityDao getSwitchsEntityDao() {
        return switchsEntityDao;
    }

}
